<?php

/**
 * Implements hook_menu().
 */
function wcmc_ors_menu() {
  $items['reporting/questionnaires'] = array(
    'title' => 'ORS questionnaires',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wcmc_ors_questionnaires_form'),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'file' => 'wcmc_ors.forms.inc',
    'type' => MENU_CALLBACK,
  );
  $items['reporting/questionnaires/%/questions'] = array(
    'title' => 'ORS questionnaire questions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wcmc_ors_questions_form'),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'file' => 'wcmc_ors.forms.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}
