version: '2'
services:
  db:
    restart: always
    image: mariadb
    volumes:
      - ../.sql/:/docker-entrypoint-initdb.d/
      - ./.docker/db/conf:/etc/mysql/conf.d/
    # Access container db from host using mysql client
    # ports:
    #  - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal

  cli:
    restart: always
    build: .docker/cli
    volumes_from:
      - web
    links:
      - db
      - web

  solr:
    image: solr:5.5
    restart: always
    # Map port to host for debugging
    ports:
      - "8983:8983"
    volumes:
      - ./.docker/solr:/opt/solr/server/solr

  web:
    restart: always
    build: .docker/web
    ports:
      - "8084:80"
    volumes:
      - ./docroot:/var/www/html
      - .docker/web/php.ini:/usr/local/etc/php/php.ini
      - ./docroot/sites/default/files:/var/www/html/sites/default/files
    # Don't start unless we have a working db instance
    depends_on:
      - db
