version: '2'
services:
  web:
    build: .docker/web
    ports:
      - "8084:80"
    volumes:
      - ./project:/var/www
  db:
    image: mariadb
    # volumes:
    #  - .docker/db/conf:/etc/mysql/conf.d/
    #  - .docker/blob/db:/var/lib/mysql/
    # ports:
    #  - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=secret
    restart: always

  cli:
    build: .docker/cli
    volumes_from:
      - web
    links:
      - db
      - web
