version: '2'
services:
  db:
    image: mariadb
    volumes:
      - ../dumps/:/docker-entrypoint-initdb.d/
    #  - .docker/db/conf:/etc/mysql/conf.d/
    #  - .docker/blob/db:/var/lib/mysql/
    # ports:
    #  - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
    restart: always

  cli:
    build: .docker/cli
    volumes_from:
      - web
    links:
      - db
      - web
  web:
    build: .docker/web
    ports:
      - "8084:80"
    volumes:
      - ./docroot:/var/www/html
      - .docker/web/php.ini:/usr/local/etc/php/php.ini
      - ./docroot/sites/default/files:/var/www/html/sites/default/files
    # Don't start unless we have a working db instance
    depends_on:
      - db
