<?php
/**
 * @file
 * cms_search.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function cms_search_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-1IZbRPsIvkqVaprT80mO3slJ0d5EcT0x'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1IZbRPsIvkqVaprT80mO3slJ0d5EcT0x',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search',
    'roles' => array(),
    'themes' => array(
      'cms_frontend' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'cms_frontend',
        'weight' => -57,
      ),
      'cms_manage' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'cms_manage',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['facetapi-CMdKaPNpQUELSbMFeop7CrP1w6I0EvuU'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'CMdKaPNpQUELSbMFeop7CrP1w6I0EvuU',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search',
    'roles' => array(),
    'themes' => array(
      'cms_frontend' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'cms_frontend',
        'weight' => -55,
      ),
      'cms_manage' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'cms_manage',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['facetapi-bhmRHTzU2n0ejKZP9wDI0S1oi2DgbSDm'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'bhmRHTzU2n0ejKZP9wDI0S1oi2DgbSDm',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search',
    'roles' => array(),
    'themes' => array(
      'cms_frontend' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'cms_frontend',
        'weight' => -58,
      ),
      'cms_manage' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'cms_manage',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['facetapi-vYpTUFJS3dzXqIEUea70igewJv0oCT62'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'vYpTUFJS3dzXqIEUea70igewJv0oCT62',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'search',
    'roles' => array(),
    'themes' => array(
      'cms_frontend' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'cms_frontend',
        'weight' => -56,
      ),
      'cms_manage' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'cms_manage',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  return $export;
}
