<?php
/**
 * @file
 * Code for the CMS Search feature.
 */

include_once 'cms_search.features.inc';

/**
 * Implements hook_form_alter().
 */
function cms_search_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'search_block_form':
      // Overwrite the search block to use the Search API view
      $form['#submit'] = array('cms_search_api_block_form_submit');
      break;
  }
}

/**
 * Callback for search block module to redirect to search page
 * with view filter argument.
 */
function cms_search_api_block_form_submit($form, $form_state) {
  drupal_goto('search', array('query' => array('search' => $form_state['values']['search_block_form'])));
}

/**
 * Implements hook_post_features_revert().
 */
function cms_search_post_features_revert($component) {
  // Set the solr server for current instance index.
  if ($component == 'search_api_index') {
    $index = search_api_index_load('default_multilingual_node_index');
    $instance = variable_get('cms_instance');
    if (!empty($instance)) {
      $index->server = $instance . '_solr';
      $index->enabled = 1;
      $index->save();

    }
  }
}